CREATE DATABASE Practica2;

SHOW DATABASES;

USE Practica2;


CREATE TABLE PACIENTE(
	idPaciente INT AUTO_INCREMENT PRIMARY KEY,
    edad int,
    genero varchar(20)
);
SELECT * FROM PACIENTE;
SELECT COUNT(*) FROM PACIENTE;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE HABITACION (
idHabitacion INT AUTO_INCREMENT PRIMARY KEY,
Habitacion varchar(50)
);
SELECT * FROM HABITACION;
SELECT COUNT(*) FROM HABITACION;



CREATE TABLE LOG_HABITACION(
	timestampx varchar(100) PRIMARY KEY,
    statusx VARCHAR(15),
    idHabitacion INT,
    FOREIGN KEY (idHabitacion) REFERENCES HABITACION(idHabitacion) ON DELETE CASCADE
);
SELECT * FROM LOG_HABITACION;
SELECT COUNT(*) FROM LOG_HABITACION;




CREATE TABLE LOG_ACTIVIDAD (
	id_log_actividad INT auto_increment PRIMARY KEY,
    timestampx VARCHAR(100),
    actividad VARCHAR(500),
    PACIENTE_idPaciente INT,
    HABITACION_idHabitacion INT,
    FOREIGN KEY (HABITACION_idHabitacion) REFERENCES HABITACION(idHabitacion) ON DELETE CASCADE,
    FOREIGN KEY (PACIENTE_idPaciente) REFERENCES PACIENTE(idPaciente) ON DELETE CASCADE
);

SELECT * FROM LOG_ACTIVIDAD;
SELECT COUNT(*) FROM LOG_ACTIVIDAD;





